name: main

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Build on Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Inject secrets
        run: |
        cd dist/js && pwd && ls -alh && sed -i -e "s/:apiid/${{ secrets.API_ID }}/g" main.js && sed -i -e "s/:apikey/${{ secrets.API_KEY }}/g" main.js
